### ISSUE TITLE
Plugin statusbar with jsuites layout showing a wrong height for the statusbar

### ISSUE THREAD

**Issue by pphod** [GBonnaire/jspreadsheet-plugins-and-editors#1]
![image](https://user-images.githubusercontent.com/6019713/94344943-b160e880-001a-11eb-8bac-f170f291e063.png)

**Comment by GBonnaire** [comment]
I think is not jsuites.js but you CSS specific with padding. 

I use jsuites with plugin, and it's ok. But, i have fixe CSS 😊
