### ISSUE TITLE
copypaste_advanced inconsistent behavior - not pasting style with CTRL+V

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#12]
### Plugin Name with version

copypaste_advanced: "3.0.3"

### JSpreadsheet version

v9.x

### Describe the bug

When pasting from Excel / Google Spreadsheet, styles get pasted correctly when pasting using toolbar or context menu, but not with CTRL+V (or CMD+V) - only values get pasted. Is there a way to configure this behavior?

### Reproduction steps

```bash
1. Copy styled data in excel
2. CTRL+V in jspreadsheet
3. Values get pasted, but not styles, but it does work well with toolbar and context menu
```

**Comment by GBonnaire** [comment]
Hi,

Error reproducted and fixed thanks.

Try last version with fix 3.0.4 on npmjs : https://www.npmjs.com/package/@jspreadsheet/copypaste_advanced
