### ISSUE TITLE
Can't paste in Firefox

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#13]
### Plugin Name with version

copypaste_advanced: "3.0.4"

### JSpreadsheet version

v9.x

### Describe the bug

When trying to paste anything in Firefox, macOS, getting this error:

Uncaught TypeError: navigator.clipboard.read is not a function
    paste index.js:512
    keydown index.js:443
[index.js:512](webpack://webapp/node_modules/@jspreadsheet/copypaste_advanced/index.js?e74f)
    paste index.js:512
    keydown index.js:443

Pasting never happens.

In Chromium on macOS there's also an error, but pasting does work:

Uncaught (in promise) DOMException: Failed to execute 'getType' on 'ClipboardItem': The type was not found
    at eval (webpack-internal:///./node_modules/@jspreadsheet/copypaste_advanced/index.js:512:41)

### Reproduction steps

```bash
1. Paste in Firefox
...
Error
```

**Comment by GBonnaire** [comment]
Hi,

I publish new version 3.0.5 to fix error message. But on firefox this plugin doesn't work with clipboard of navigator. The clipboard read is reserved to extension of firefox, from windows, you need paste with Ctrl + V

If you found an example who work on firefox, i will integrate on this plugin
