### ISSUE TITLE
Add row/column happens in wrong place

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#15]
### Plugin Name with version

"@jspreadsheet/statusbar": "2.2.1"

### JSpreadsheet version

v9.x

### Describe the bug

If I have cell B2 selected and I add column to the right, it gets added not into column 3, but column 4, same for other direction and same for rows - all are off by one basically.

**Comment by GBonnaire** [comment]
Hi,

I was unable to reproduce the problem. Try with last version 2.3.1 and keep me touch

**Comment by dmt0** [comment]
Hi @GBonnaire, I actually am on 2.3.1. I'm talking about a case when you have just one cell selected (not whole row or column).

**Comment by GBonnaire** [comment]
Ok

Currently, if you select only 1 cell, after click on button add row/column you add to start or to end. If you want add close row/column you need select 1 row or 1 column and after click on add.

I saw with Przemek, i will add an option to make alwayse close insertion

**Comment by GBonnaire** [comment]
Try version 2.3.2 with option `closeInsertionOnly: true,`
