### ISSUE TITLE
Seeing a console output when adding rows

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#16]
### Plugin Name with version

2.3.3

### JSpreadsheet version

v9.x

### Describe the bug

Things like `1 1 1 [1]`

![image](https://user-images.githubusercontent.com/2717746/214439099-0a73f7b5-416c-4bfe-8486-eb04a1c825f8.png)

**Comment by GBonnaire** [comment]
Thanks. It's fixed on 2.3.4

Have good day
