### ISSUE TITLE
Feature request: disable add row/col buttons when nothing is selected and closeInsertionOnly: true,

### ISSUE THREAD

**Issue by pmkrawczyk** [GBonnaire/jspreadsheet-plugins-and-editors#18]
It would be great if buttons were disabled when nothing is selected in the closeInsertionOnly mode. Otherwise user does not know where rows/cols will be inserted. This is actually a problem with JSpreadsheet - it forgets selection when switching between grids and when component looses focus. Maybe this behavior could be optional as well?

**Comment by GBonnaire** [comment]
Hi,

it's noted, I'll add it on the next version 😊

I'm keeping this post open and I'll let you know when it's updated.

**Comment by GBonnaire** [comment]
Try last version 😊

**Comment by dmt0** [comment]
Any chance we could have some visual indication for when they are disabled? Some CSS class assigned to disabled buttons would be great too, that way we could style it ourselves! Thank you!

**Comment by GBonnaire** [comment]
Hi,

oh ok, i thought it was just disable adding.

I plan that on next version. And I'll let you know when it's updated. ok ?

**Comment by GBonnaire** [comment]
Please try new version 2.4.0

new options and new events to manage actions bar 😊 

Have good day

**Comment by dmt0** [comment]
Hey, so I see the new option `autoButtonDisable`. When I enable it and select/deselect stuff. I don't see any changes to the DOM, so I still don't see any way to style those buttons.

**Comment by GBonnaire** [comment]
You are a class « disabled » who are added on parent div of buttons

You can also see events when this buttons are disable or enable.

by default the class disable make : display:none, you can overwrite this style 😊

**Comment by GBonnaire** [comment]
And small detail : This option work only with option close insertion set to true. Actually, if button can make an action this options will be check and after class added or not

**Comment by dmt0** [comment]
So I have this:
`"@jspreadsheet/statusbar": "2.4.0",`

yarn install, build, refresh the page. So I have the right version for sure.

And this in my config:

```javascript
        {
          name: 'statusbar',
          plugin: statusbar,
          options: {
            showAddRowButton: true,
            showAddColButton: true,
            autoButtonDisabled: true,
            closeInsertionOnly: true,
            defaultQuantity: 1,
            formulas: {
              ...
            },
          },
        },
```

I went to the bottom of the sheet and clicked away (so nothing is selected).
I click the buttons, nothing gets inserted, so they are disabled for sure, but looking at the DOM - no classes:

![image](https://user-images.githubusercontent.com/2717746/218189187-af774459-ca3e-4c6c-b080-4b86ec1bd931.png)

Am I looking at the wrong place?

**Comment by GBonnaire** [comment]
Do you have any error ?

On my version it work fine.

**Comment by GBonnaire** [comment]
You have an error on option name :

`autoButtonDisable` not `autoButtonDisabled`

But it change nothing this error because, by default, it’s set to true

**Comment by dmt0** [comment]
Right! Thank you! All works great now.
