### ISSUE TITLE
statistics plugin docs

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#19]
Hi @GBonnaire 
I'm not finding docs for this plugin: https://repo.gbonnaire.fr/product/jss-formulas-statistics
Also the link to statistics plugin in your root readme is a dead link

**Comment by GBonnaire** [comment]
Hi,

You can find documentation here : https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/wiki/Premium-plugin-:-Formulas-statistics
