### ISSUE TITLE
Statusbar example - Can you send examples on the options for the statusbar?

### ISSUE THREAD

**Issue by pphod** [GBonnaire/jspreadsheet-plugins-and-editors#2]
```
<script>
jexcel(document.getElementById('spreadsheet'), {
    minDimensions: [10,10],
    license: 'YjQzMzdlOTRiOGY3ZTQ0ZDQ4ZTI1YWU3MDFjMDI0ZWJmOTNjODA1NWFiZTRiNDJhNmRiYTJlZjkwODQ3N2IwMWRmNWRjYWUwZDViM2VhMmI3NzVjOTcwMzVlN2ZhODI1Y2EyMmE3NDI0ZmE0ZjVmNGQ2MWEzN2M3MTA4MThhMDUsZXlKdVlXMWxJam9pY0dGMWJDNW9iMlJsYkNJc0ltUmhkR1VpT2pFMk16SXdPVEkwTURBc0ltUnZiV0ZwYmlJNld5SnFjMlpwWkdSc1pTNXVaWFFpTENKcVpYaGpaV3d1Ym1WMElpd2lZMjlrWlhOaGJtUmliM2d1YVc4aUxDSnFjMmhsYkd3dWJtVjBJaXdpTVROemQyMHVZM05pTG1Gd2NDSXNJbXh2WTJGc2FHOXpkQ0pkTENKd2JHRnVJam9pTXlKOQ==',
    plugins: [{
        name:'statusbar',
        plugin:jexcel_statusbar
    }]
});
</script>
```

**Comment by GBonnaire** [comment]
Yes, i will create a wiki with documentation.

But, on waiting, you have 2 options :
`showAddRowButton` : boolean : For show add with input number of rows on left
`text_AddRowButton` : string : Text for button + input ( {*} = input box, by default : Add {*} row(s)
`formulas` : object with key = Title, value = formula. and in formula you have quick reference that you can use between { }. Each property = 1 information showing on selection on status bar

For example :
formulas: {
             "Range":"{range}", // Format A1:B5
             "SUM":"=SUM({range})",
             "MAX":"=MAX({range})",
             "MIN":"=MIN({range})"
         },

Quick reference
- range
- x1
- x2
- y1
- y2

did you have other question on this plugin ?

**Comment by GBonnaire** [comment]
Documentation is here : https://github.com/Guillaume-Bo/jexcel-plugins-and-editors/blob/master/plugins/statusbar/README.md
