### ISSUE TITLE
STUDENTSTTEST formula - parameters not documented in fromula description

### ISSUE THREAD

**Issue by tp-development** [GBonnaire/jspreadsheet-plugins-and-editors#20]
### Plugin Name with version

jss-formulas-statistics: 2.0.4

### JSpreadsheet version

v9.x

### Describe the bug

Documentation for formulas (https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/wiki/Premium-plugin-:-Formulas-statistics#documentations-formulas). Documentation for STUDENTSTTEST (similar issues for other formulas). Not all optional parameters are documented - see below - not clear what they control and what are their default values:
1. ScaleOfFirstColumn (optional, default=??) 
2. ScaleOfSecondColumn (optional, default=)  
3. Epsilon (optional, default=)
4. SpougeConstant (optional, default=) 

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by GBonnaire** [comment]
Hi,

I have make an update about documentation with default value, example: [alpha=0.25]

New version will be deployed in some hours.

**Comment by GBonnaire** [comment]
new version 2.0.6 are available with new documentation with default value.

+ New options for scale : you can use `SCALE.NOMINAL()` or `SCALE.ORDINAL()` or `SCALE.INTERVAL()` or `SCALE.METRIC()` direct in formula arguments like ScaleOfDegree

Have good day

**Comment by tp-development** [comment]
Thanks for adding these default values, however, I am still missing the description of these parameters. What do they actually control? Thanks for completing the documentation with the descriptions!
