### ISSUE TITLE
STUDENTSTTESTONESAMPLE generates an error

### ISSUE THREAD

**Issue by tp-development** [GBonnaire/jspreadsheet-plugins-and-editors#21]
### Plugin Name with version

jss-formulas-statistics: 2.0.4

### JSpreadsheet version

v9.x

### Describe the bug

I tried to use =STUDENTSTTESTONESAMPLE.TSTATISTIC(A13:A22,B13) in C13 / (See the screenshot below).
It is returning an error (despite that the other formulas of the family STUDENTSTTESTONESAMPLE work).
![image](https://user-images.githubusercontent.com/98662312/230445336-092b95ff-ef5c-4585-a26a-c95377021449.png)

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by GBonnaire** [comment]
Please Use 2.0.5 or up who fix this bug :

<img width="651" alt="image" src="https://user-images.githubusercontent.com/52194475/230573612-ddb26f0d-9fde-4b40-a3b9-747082ebbd6f.png">

**Comment by GBonnaire** [comment]
new version 2.0.6 are available with new documentation with default value.

+ New options for scale : you can use `SCALE.NOMINAL()` or `SCALE.ORDINAL()` or `SCALE.INTERVAL()` or `SCALE.METRIC()` direct in formula arguments like ScaleOfDegree

Have good day

**Comment by tp-development** [comment]
I use 2.0.6 and still got the bug, please see and let me know if I need to reopen an issue: 
 
![image](https://user-images.githubusercontent.com/98662312/231572362-7e51dcdf-42a7-4550-bc10-04c7edefae5a.png)

**Comment by GBonnaire** [comment]
I have tested : And it's work on my version 2.0.6.

Could you verify on your cache browser if you have 2.0.6 or CTRL+F5 to refresh with clean cache page ? And if bug is already present, do you have an error on console browser ?

**Comment by tp-development** [comment]
Yep, clearing browser cache helped apparently.
