### ISSUE TITLE
Extending scope of formula parameter documentation

### ISSUE THREAD

**Issue by tp-development** [GBonnaire/jspreadsheet-plugins-and-editors#23]
**Please consider extending the structure of the parameter description**. Currently based on documentation:
https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/wiki/Premium-plugin-:-Formulas-statistics#formula-documentation 
we have the following attributes documented for a parameter:
- type - type of the parameter
- comment - parameter description
**I would consider extending it for the following new ones:**
- **array** - Boolean information on whether the parameter is of vector or scalar type
- **mandatory** - Boolean information on whether the parameter is optional or mandatory;
- **default** - the default value for the parameter;
- **possible values** - the set of possible values ;

**Comment by GBonnaire** [comment]
Document have been updated.

Have good day 😊
