### ISSUE TITLE
Errors on invocations statistical test functions (Student, Chi, Binominal)

### ISSUE THREAD

**Issue by tp-development** [GBonnaire/jspreadsheet-plugins-and-editors#24]
### Plugin Name with version

jss-formulas-statistics: 2.0.6

### JSpreadsheet version

v9.x

### Describe the bug

formula-pro: 3.0.2,
jss-formulas-statistics: 2.0.6
jss-plugin-formula: 2.3.1

for statistical test formulas, I am getting an error, though I try to apply them to the example given in the documentation. See screenshots below:

![image](https://user-images.githubusercontent.com/98662312/236635505-293be854-19b1-4fbe-8318-869abcfe37e4.png)
<img width="960" alt="ChiSquareTestError" src="https://user-images.githubusercontent.com/98662312/236635619-b4db9545-6b95-4155-a361-a41d73800f08.png">
<img width="947" alt="BinominalTestError" src="https://user-images.githubusercontent.com/98662312/236635373-7b30579b-1b5d-4393-b081-e5589a554dea.png">
![image](https://user-images.githubusercontent.com/98662312/236672993-a92a6103-4aaa-4126-840d-324c9ff3df87.png)

### Reproduction steps

```bash
1. Try to replicate the example from Statistic.js
2.
```

**Comment by GBonnaire** [comment]
Hi,

It's noted, i analyse why et come back when it's fixed.

In waiting, you can use version 2.9.0 of formula-pro (it's work)

**Comment by GBonnaire** [comment]
With version of formula-pro 3.0.3 it's fixed. Please update and can you confirm we have no errors ?

**Comment by tp-development** [comment]
Works fine, we can close the issue.
