### ISSUE TITLE
statistics plugin 2.1.0 docs display regression

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#25]
### Plugin Name with version

"@progidev/jss-formulas-statistics": "2.1.0"

### JSpreadsheet version

v9.x

### Describe the bug

In 2.0.6 as I type the formula name in the cell, like "=STUDENTSTTESTONESAMPLE" as I finish typing the name, or type '.', I get a popup with documentation for the formula. This does not happen with 2.1.0. It works for some formulas but not for all.

**Comment by GBonnaire** [comment]
Hi,

If you use your own documentation, can you check if function name is egale to new functions names in 2.1 ?

Some functions was been name

**Comment by dmt0** [comment]
Yeah, saw the new function names, thanks!
