### ISSUE TITLE
Question: is it possible to remove formulas via config?

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#29]
### Plugin Name with version

"@progidev/jss-formulas-statistics": "2.1.2"

### JSpreadsheet version

v9.x

### Describe the bug

I basically want to make certain formulas unavailable to users.
Is there a way of doing this?

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by GBonnaire** [comment]
Hi,

No, you can't.

After on init of jspreadsheet, you can remove some formula and refresh documentation of plugin formula editors

```javascript
delete(formula['TTEST']);
jspreadsheet.current.parent.plugins.formula.refreshDoc();
```
