### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by MartinDawson** [GBonnaire/jspreadsheet-plugins-and-editors#3]
Hi,

Could the statusBar plugins be added to an npm package please? And made es6 import compatible

Thanks

**Comment by GBonnaire** [comment]
Hi,

Now plugin is es6 compatible. If you have bug, you can create issue for fix.

for NPM, coming soon on @jspreadsheet/statusbar (it was with JSpreadsheet v8). But i will publish in very soon on npm

**Comment by GBonnaire** [comment]
Hi,

in waiting you can use this package on NPM : `jspreadsheet-plugin-statusbar`

I publish others plugins soon and you can (soon too) install package with local file without npm store

**Comment by GBonnaire** [comment]
Try that : 

1. download git file on your server
2. execute this command

```shell
cd /path/to/git/plugins
# npm install ./<pluginName>
npm install ./statusbar
```
