### ISSUE TITLE
STUDENT T-TEST PAIRED/ Discrepancies in calculation with MS Excel

### ISSUE THREAD

**Issue by tp-development** [GBonnaire/jspreadsheet-plugins-and-editors#30]
### Plugin Name with version

3.2.2

### JSpreadsheet version

v9.x

### Describe the bug

See a spreadsheet with an example - there is still a discrepancy between Excel and stat package:
https://docs.google.com/spreadsheets/d/1oBX-outkj2eX-kpwMW_bfOlwV_PCm6y3/edit?usp=sharing&ouid=105291088824732366674&rtpof=true&sd=true

- "@progidev/jss-formulas-statistics": "2.2.1"
- "@progidev/jss-plugin-formula": "2.3.5"
- "@jspreadsheet/formula-pro": "3.2.2"

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by GBonnaire** [comment]
Hi, 

It's a difference because you compare paired result with unpaired result, on plugin, i have implemented only unpaired values. i search to implement paired

**Comment by GBonnaire** [comment]
I found a solution 😊 i will be available on 2.2.2

Warning : New syntax of formula TTEST
`=TTEST.TWOSAMPLES.T(A1:A100,B1:B100,FALSE)`

TTEST.TWOSAMPLES.T(firstColumn &rarr; Range, secondColumn &rarr; Range, [pairedValue = FALSE])

**Comment by tp-development** [comment]
Do we need the additional parameter? There was already a parameter _dependant_ which was to indicate that samples are paired(?), wasn't it?

**Comment by GBonnaire** [comment]
`dependance` is replace by `pairedValue`

You have now 3 parameters : 
firstColumn : Sample1
SecondColumn: Sample2
pairedValue : Indicate if values are dependant or not

**Comment by tp-development** [comment]
Ok, that makes sense. I was wondering if the name shouldn't be _pairedSamples_  instead of _pairedValue_ (because we have multiple values here, and the user might not be sure which value is meant here).

**Comment by GBonnaire** [comment]
Ok, i will change 👍
You prefere :
- pairedSample ?
- Dependant ?

**Comment by tp-development** [comment]
my vote goes to: _pairedSamples_  (true/false) :)

**Comment by GBonnaire** [comment]
It's on line on v2.2.3 😊

**Comment by tp-development** [comment]
After attaching 2.2.3 the changes are not visible (lack of the new parameter).
