### ISSUE TITLE
WINSORISEDMEAN / Discrepancies in calculation with MS Excel

### ISSUE THREAD

**Issue by tp-development** [GBonnaire/jspreadsheet-plugins-and-editors#31]
### Plugin Name with version

3.2.2

### JSpreadsheet version

v9.x

### Describe the bug

There are discrepancies in MEAN.WINSORISED between the package and excel. See the attached spreadsheet.

https://docs.google.com/spreadsheets/d/1z1wDxLnvS6gHE_ntpFmOEUQfryo7soaN/edit?usp=sharing&ouid=105291088824732366674&rtpof=true&sd=true

"@progidev/jss-formulas-statistics": "2.2.1",
"@progidev/jss-plugin-formula": "2.3.5",
"@jspreadsheet/formula-pro": "3.2.2",

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by GBonnaire** [comment]
Hi,

I have a same result of this site : https://www.mathcelebrity.com/trimmedmean.php?num=-9%2C10%2C-21%2C-5%2C-14%2C7%2C-47%2C20%2C28%2C-43%2C9%2C-21%2C44%2C37%2C43%2C-21%2C4%2C-6%2C26%2C-42%2C7%2C42%2C0%2C-46%2C-14%2C-26%2C-34%2C-37%2C-27%2C18%2C20%2C19%2C-42%2C48%2C10%2C-40%2C23%2C15%2C42%2C-18%2C-18%2C25%2C-43%2C-11%2C-37%2C-22%2C-10%2C-31%2C48%2C35%2C2%2C-40%2C41%2C23%2C6%2C-49%2C-35%2C27%2C-46%2C4%2C-34%2C31%2C-29%2C50%2C21%2C-42%2C-34%2C-47%2C-7%2C-14%2C-35%2C-19%2C32%2C25%2C14%2C-14%2C43%2C11%2C46%2C-26%2C47%2C11%2C11%2C38%2C-18%2C14%2C-38%2C34%2C-39%2C10%2C-15%2C42%2C0%2C45%2C-44%2C-32%2C-26%2C38%2C17%2C18%2C-34%2C12%2C-30%2C1%2C-22%2C-37%2C-18%2C-33%2C-11%2C30%2C37%2C36%2C36%2C-20%2C24%2C8%2C5%2C47%2C22%2C12%2C44%2C8%2C-46%2C30%2C-15%2C-16%2C-38%2C21%2C-40%2C-36%2C-33%2C-3%2C-37%2C19%2C-10%2C-49%2C3%2C50%2C-40%2C-17%2C-4%2C-43%2C-48%2C-7%2C10%2C23%2C49%2C0%2C-28%2C-34%2C28%2C12%2C-30%2C-45%2C-24%2C-36%2C-9%2C-5%2C9%2C-3%2C16%2C22%2C-18%2C37%2C-10%2C-31%2C-10%2C-46%2C41%2C46%2C-11%2C-44%2C36%2C-28%2C-19%2C-17%2C19%2C46%2C25%2C-20%2C-3%2C-49%2C26%2C35%2C31%2C-28%2C-32%2C28%2C-12%2C-27%2C17%2C-30%2C-8%2C20%2C-28%2C-7%2C-29%2C-44%2C41%2C-25%2C5%2C-35%2C-25%2C34%2C14%2C0%2C1%2C10%2C30%2C-36%2C1%2C2%2C48%2C-13%2C2%2C-12%2C-18%2C3%2C30%2C41%2C36%2C-25%2C45%2C-45%2C-18%2C9%2C50%2C-15%2C17%2C50%2C46%2C6%2C-45%2C40%2C-36%2C49%2C15%2C3%2C-48%2C37%2C-12%2C-11%2C-42%2C35%2C26%2C-1%2C-12%2C-32%2C2%2C-13%2C36%2C-37%2C39%2C34%2C-29%2C33%2C-17%2C24%2C50%2C42%2C46%2C-19%2C13%2C19%2C37%2C10%2C19%2C10%2C31%2C-19%2C-40%2C15%2C49%2C24%2C12%2C4%2C-34%2C49%2C24%2C21%2C-11%2C48%2C32%2C3%2C-38%2C-18%2C-9%2C7%2C-29%2C-8%2C-26%2C-32%2C-23%2C-41%2C24%2C-4%2C6%2C10%2C22%2C42%2C-15%2C34%2C-39%2C-35%2C-37%2C11%2C34%2C33%2C-47%2C-49%2C32%2C37%2C45%2C-26%2C24%2C25%2C-14%2C-13%2C35%2C26%2C22%2C-1%2C-16%2C-11%2C-12%2C8%2C-26%2C46%2C48%2C-32%2C16%2C-12%2C-33%2C-29%2C25%2C41%2C-7%2C-3%2C25%2C-29%2C21%2C17%2C-11%2C44%2C0%2C-36%2C-24%2C6%2C45%2C-25%2C-11%2C25%2C10%2C32%2C-27%2C42%2C34%2C15%2C-29%2C15%2C-1%2C-19%2C-27%2C50%2C-3%2C44%2C17%2C-3%2C-43%2C7%2C46%2C16%2C33%2C26%2C-40%2C-4%2C14%2C41%2C46%2C-12%2C-8%2C3%2C-25%2C47%2C19%2C-20%2C34%2C-8%2C30%2C-20%2C23%2C50%2C34%2C46%2C36%2C14%2C-9%2C-49%2C-37%2C1%2C6%2C-7%2C-15%2C-16%2C37%2C43%2C-19%2C45%2C-21%2C7%2C38%2C2%2C-17%2C-3%2C-5%2C1%2C37%2C-13%2C-6%2C-14%2C-5%2C12%2C-26%2C19%2C2%2C-7%2C-13%2C2%2C12%2C-25%2C-16%2C1%2C0%2C29%2C-8%2C34%2C25%2C41%2C23%2C-25%2C-10%2C-39%2C13%2C36%2C-5%2C3%2C26%2C-7%2C-30%2C33%2C38%2C38%2C-46%2C-5%2C40%2C36%2C50%2C-45%2C23%2C-13%2C43%2C21%2C-2%2C30%2C-43%2C-3%2C-31%2C40%2C-2%2C41%2C16%2C-43%2C21%2C48%2C-48%2C-36%2C23%2C49%2C-27%2C-19%2C-36%2C28%2C-14%2C20%2C16%2C50%2C-15%2C-42%2C-25%2C1%2C21%2C-38%2C25%2C-18%2C-6%2C-6%2C-5%2C-27%2C-9%2C-16%2C21%2C10%2C30%2C-20%2C-40%2C-38%2C-35%2C17%2C-35%2C21%2C-44%2C26%2C29%2C-4%2C-1%2C7%2C-16%2C39%2C-17%2C-2%2C-26%2C26%2C7%2C-27%2C42%2C-9%2C16%2C45%2C46%2C14%2C17%2C-26%2C-2%2C26%2C16%2C-3%2C-9%2C4%2C-19%2C-15%2C-15%2C-26%2C18%2C18%2C-33%2C-18%2C-24%2C50%2C22%2C15%2C18%2C22%2C-15%2C-16%2C-26%2C9%2C31%2C41%2C-21%2C42%2C-36%2C-35%2C27%2C21%2C17%2C-36%2C-43%2C-38%2C-43%2C-32%2C-13%2C-3%2C-48%2C-10%2C-41%2C-20%2C-12%2C5%2C-9%2C22%2C9%2C-12%2C-13%2C34%2C-27%2C-13%2C5%2C38%2C18%2C-4%2C-10%2C41%2C-26%2C-15%2C36%2C17%2C13%2C-22%2C-45%2C-31%2C-25%2C48%2C-11%2C-31%2C41%2C0%2C7%2C35%2C20%2C-42%2C-1%2C28%2C-49%2C22%2C20%2C-8%2C-28%2C-46%2C34%2C-20%2C-14%2C-37%2C-32%2C14%2C5%2C29%2C47%2C-40%2C44%2C-13%2C-25%2C-7%2C-6%2C-32%2C-38%2C-12%2C21%2C-46%2C-21%2C37%2C29%2C10%2C35%2C-15%2C-41%2C-17%2C1%2C43%2C-20%2C-19%2C-1%2C-37%2C15%2C10%2C37%2C37%2C-31%2C-38%2C-12%2C-4%2C34%2C-11%2C5%2C15%2C-39%2C46%2C-28%2C-24%2C26%2C-33%2C20%2C43%2C11%2C8%2C-5%2C45%2C-33%2C35%2C13%2C-25%2C-16%2C35%2C-40%2C-31%2C-48%2C-29%2C-47%2C49%2C-32%2C-47%2C15%2C-5%2C4%2C-44%2C-11%2C-30%2C9%2C-29%2C-25%2C-27%2C49%2C32%2C-17%2C22%2C-7%2C4%2C44%2C31%2C-29%2C-41%2C-45%2C36%2C46%2C-18%2C32%2C36%2C2%2C16%2C18%2C-23%2C36%2C2%2C-37%2C0%2C-19%2C-26%2C23%2C35%2C-30%2C23%2C21%2C-18%2C-22%2C-43%2C-38%2C44%2C-40%2C39%2C-47%2C0%2C-42%2C45%2C31%2C-36%2C-27%2C-25%2C-3%2C-32%2C-19%2C48%2C-25%2C-32%2C-18%2C47%2C-6%2C-7%2C-39%2C37%2C26%2C-6%2C9%2C23%2C-12%2C24%2C-1%2C6%2C4%2C37%2C-33%2C19%2C6%2C40%2C50%2C-27%2C48%2C38%2C-32%2C-24%2C-20%2C-34%2C5%2C-16%2C-17%2C48%2C39%2C-34%2C37%2C-38%2C-9%2C-45%2C-33%2C2%2C48%2C-24%2C41%2C-11%2C-36%2C-12%2C19%2C7%2C-18%2C22%2C12%2C-27%2C-22%2C19%2C-25%2C-46%2C30%2C-48%2C-46%2C-42%2C15%2C-48%2C-9%2C-48%2C-22%2C-2%2C-40%2C9%2C-18%2C26%2C9%2C-45%2C12%2C-40%2C-34%2C-45%2C33%2C34%2C0%2C-16%2C-4%2C-9%2C-26%2C-3%2C27%2C19%2C25%2C15%2C33%2C33%2C29%2C19%2C36%2C-11%2C-20%2C-37%2C29%2C12%2C48%2C16%2C-9%2C4%2C-14%2C20%2C19%2C-43%2C4%2C28%2C-11%2C-10%2C0%2C25%2C5%2C-48%2C11%2C25%2C-15%2C50%2C32%2C11%2C-25%2C15%2C-24%2C10%2C-47%2C15%2C27%2C7%2C-14%2C6%2C34%2C-13%2C21%2C28%2C-8%2C11%2C33%2C23%2C-36%2C-38%2C23%2C22%2C-39%2C18%2C13%2C-49%2C-34%2C-34%2C44%2C-17%2C-19%2C5%2C-41%2C7%2C-21%2C34%2C-31%2C11%2C2%2C-46%2C19%2C22%2C6%2C-47%2C-37%2C-48%2C-35%2C3%2C-32%2C-24%2C10%2C17%2C10%2C-31%2C10%2C-1%2C-9%2C6%2C-4%2C-34%2C-36%2C-35%2C-31%2C-29%2C22%2C-28%2C35%2C-12%2C0%2C11%2C45%2C-26%2C27%2C-9%2C-22%2C25%2C5%2C40%2C31%2C46%2C26%2C22%2C-6%2C-37%2C-4%2C15%2C28%2C50%2C-35%2C46%2C-26%2C-39%2C-20%2C39%2C-48%2C-2%2C-41%2C-9%2C23%2C-42%2C-39%2C-48%2C-16%2C-17%2C43%2C13%2C-5%2C-25%2C-28%2C-24%2C-18%2C-19%2C-22%2C-19%2C49%2C19%2C-38%2C12%2C46%2C18%2C0%2C8%2C7%2C-16%2C-2%2C19%2C-17%2C-6&tmpct=20&pl=Winsorized+Mean

What is a percentage use  ?

By default on plugin it's 20%

**Comment by tp-development** [comment]
Yep, I've checked your example and the exact definition - works fine. I close the issue
