### ISSUE TITLE
Cut Copy Pasted toolbar position

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#33]
### Plugin Name with version

"@jspreadsheet/copypaste_advanced": "3.0.5",

### JSpreadsheet version

v9.x

### Describe the bug

I build a custom toolbar in jspreadsheet. The problem is I can't control the position at which cut, copy, paste buttons get inserted. Here's my toolbar function that goes into jspreadsheet config:

```javascript
    toolbar: (toolbar) => ({
        ...toolbar,
        items: [
          {
            tooltip: 'Download as Excel spreadsheet',
            content: 'file_download',
            onclick: () => { ...},
          },
          {
            tooltip: 'Import a grid',
            content: 'file_upload',
            onclick: () => ...,
          },
          {type: 'divisor'},
          toolbar.items[0], // Undo
          toolbar.items[1], // Redo
          // Cut copy paste get inserted here for some reason. No idea when. !!!!!!!!!!!!!!!!
          {type: 'divisor'},
          // Font
          toolbar.items[4], // Font
          toolbar.items[5], // Font size
          toolbar.items[7], // Bold
          {
            type: 'i',
            content: 'format_italic',
            onclick: () => {
              that
                .getCurrentJssSheet()
                .setStyle(that.getCurrentJssSheet().getSelected(), 'font-style', 'italic');
            },
          },
          {type: 'divisor'},
          // Color text and fill
          toolbar.items[8],
          toolbar.items[9],
          {type: 'divisor'},
          // Alignment
          toolbar.items[6],
          toolbar.items[10],
          {type: 'divisor'},
          // Borders and Full Screen
          toolbar.items[12],
          toolbar.items[14],
          {type: 'divisor'},
          // Search
          toolbar.items[15],
        ],
      }),
```

I indicated by the comment where the buttons get inserted, here's also the screenshot:
![image](https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/2717746/a6acde15-57a5-43c1-b7d7-1c6d6fd3a33a)

If I follow your Readme example and manually insert the buttons, I get two copies of the buttons.

The `toolbar` argument of the function above does not contain the cut/copy/paste buttons at all. So not sure when they get inserted.

What I want to do is add them at a different position and have another divisor before them, but they always get into positions 5,6,7.

**Comment by GBonnaire** [comment]
Hi, 

Could you try new version 3.1.0 ?

In this version, you have a new property : position_toolbar

null : default behavior
false : not show
int: position specifics

**Comment by dmt0** [comment]
Works like a charm!
```javascript
{name: 'copypaste_adv', plugin: jss_copypaste_advanced, options: {position_toolbar: 5}},
```
![image](https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/2717746/d362c5ad-aeb0-4bf9-83c7-04ffca47b688)
