### ISSUE TITLE
jspreadsheet version to be specified as peerDependency

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#34]
### Plugin Name with version

All plugins

### JSpreadsheet version

v9.x

### Describe the bug

My project is currently on jspreadsheet v9 and I can't upgrade to v10 because of bugs in v10.

But my yarn.lock contains both V9 and V10, which reflects on my bundle size, because some of your plugins specify jspreadsheet as a `dependency` with version >8 or >9, which both resolve to 10.

I don't think I can do much about it on my side. But if you'd specify it as a `peerDependency` in the same way, your plugins would just use whatever I already have in yarn.lock. I think that would be a better way.

Thanks!

**Comment by GBonnaire** [comment]
Hi,

Yes, new version will be available on v10 soon. And with this new version Dependancy will be specified.

**Comment by dmt0** [comment]
Hi Guillaume, I'm saying the opposite thing. I'm _not_ on v10, and I want to stay on v9 (and maybe other people want to do that too, and the same happens with each version bump, not everyone wants to upgrade right away), but because I use your plugins, v10 gets included in my bundle, together with my v9, and makes my bundle bigger.

But if you use `peerDependency` instead of `dependency`, your plugins will just use whatever I already have in _my_ package.json and not force install latest major version.

**Comment by GBonnaire** [comment]
Hi,

Yes i understood well, current version will be receive dependency or peerDependency and new version will be on specifics plugin

I keep touch you when is online; i work tomorrow on that

**Comment by GBonnaire** [comment]
Can you check ? all versions have peerDependencies in package and limit version about JSS

**Comment by GBonnaire** [comment]
Fixed on plugins premium and free
