### ISSUE TITLE
Print Area Selection Options Not Working

### ISSUE THREAD

**Issue by stephen-taylor-dev** [GBonnaire/jspreadsheet-plugins-and-editors#35]
### Plugin Name with version

Print Version 2.1.0

### JSpreadsheet version

v9.x

### Describe the bug

The "Print Area" options to "Print all rows of the sheet" and "Print Selection" are not working as expected. Trying to print out all of the rows or a selection on a specific worksheet tab only prints out information from the first worksheet tab in the spreadsheet regardless of which tab you have currently selected. 

I'm running Jspreadsheet v9.5.0

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by GBonnaire** [comment]
Hi,

Thanks, reproducted and fixed on 2.1.1. Please update
