### ISSUE TITLE
Print Formatting and Layout Issue when printing all worksheets

### ISSUE THREAD

**Issue by stephen-taylor-dev** [GBonnaire/jspreadsheet-plugins-and-editors#36]
### Plugin Name with version

Print Version 2.1.0

### JSpreadsheet version

v9.x

### Describe the bug

When printing out all worksheets in a spreadsheet, there seems to be a print formatting and layout bug when printing worksheet tabs that have not been clicked on prior to printing. Every tab you click on and view before printing is formatted correctly when printed. The issue seems to only come up on tabs that have not been clicked on prior to printing.

This screenshot shows how it is formatted and structured in Jspreadsheet.
<img width="1365" alt="Screenshot 2023-08-08 at 2 17 16 PM" src="https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/47441158/576e55f2-7e73-4c43-a100-4a37534094c5">

This shows how the print plugin displays the layout and formatting.
<img width="583" alt="Screenshot 2023-08-08 at 2 17 02 PM" src="https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/47441158/e01c407f-2f09-4096-a106-4eae11b12cf0">

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by GBonnaire** [comment]
Hi,

Can you share configuration of worksheets, i don't reproduct on my version this bug

**Comment by stephen-taylor-dev** [comment]
Ok, I just discovered I can only replicate it when I render the Jspreadsheet content into an element set to "display: none;". When I then set it to "display: block;", open the spreadsheet with "spreadsheet[0].openWorksheet()" and click print, it displays like the second picture from above. Otherwise it works as expected.

**Comment by GBonnaire** [comment]
Can you tell me, what is element is set to display: none ? columns ?

If i can reproduct, maybe i can understand why and maybe fix 😊

**Comment by GBonnaire** [comment]
Close for inactivity
