### ISSUE TITLE
Hidden columns showing up in print for spreadsheets with many columns

### ISSUE THREAD

**Issue by stephen-taylor-dev** [GBonnaire/jspreadsheet-plugins-and-editors#37]
### Plugin Name with version

Print Version 2.1.2

### JSpreadsheet version

v9.x

### Describe the bug

I'm experiencing an issue with the print plugin when printing large spreadsheets with many that have hidden columns. It happens when one of the last of many columns is hidden and then when printing "all rows of the spreadsheet", some of the data from the hidden column will show up in the neighbor column of the spreadsheet or sometimes outside of the print area.

Here is an example file that causes the issue. https://viztech360-my.sharepoint.com/:x:/p/stephen/EaRupSRL07BEoUmP8Yrnq9ABWSFfQwurj1tn4Asof76WwA?e=iodLjs

Please let me know if this is something you can replicate. 

Thanks,
Stephen

### Reproduction steps

```bash
1. Import the example spreadsheet (https://viztech360-my.sharepoint.com/:x:/p/stephen/EaRupSRL07BEoUmP8Yrnq9ABWSFfQwurj1tn4Asof76WwA?e=iodLjs)
2. Hide column "O"
3. Print "all rows of sheet"
4. See if any data from Column "O" appears in column "P" or elsewhere on print out.
```

**Comment by GBonnaire** [comment]
Hi,

Thanks for signaling. This bug is fixed on 2.1.3.
