### ISSUE TITLE
Error on Print

### ISSUE THREAD

**Issue by stephen-taylor-dev** [GBonnaire/jspreadsheet-plugins-and-editors#38]
### Plugin Name with version

Print Version 2.1.3

### JSpreadsheet version

v9.x

### Describe the bug

Thanks for the quick fix on the other issueQ

When I try to print anything I am getting this error. I am still running Jspreadsheet V9.

```
jss.print.js:146 Uncaught ReferenceError: worksheet is not defined 
    at Object.x (jss.print.js:146:3726)
    at l.do (jss.print.js:87:2187)
    at p.content.querySelector.onclick (jss.print.js:146:1292)


x @ jss.print.js:146
l.do @ jss.print.js:87
p.content.querySelector.onclick @ jss.print.js:146
```

Thanks,
Stephen

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by GBonnaire** [comment]
Sorry bad push, it's fixed
