### ISSUE TITLE
Can't install with 'bun'

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#39]
### Describe the bug

In my package.json:
```
...
    "@progidev/jss-formulas-statistics": "2.2.7",
    "@progidev/jss-plugin-formula": "2.3.5",
...
```

Terminal:
```
bun install
bun install v1.0.1 (31aec4eb)
  🔍 @progidev/jss-formulas-statistics [3/300] 
error: package "@progidev/jss-formulas-statistics" not found registry.npmjs.org/@progidev/jss-formulas-statistics 404
  🔍 @progidev/jss-plugin-formula [4/300] 
error: package "@progidev/jss-plugin-formula" not found registry.npmjs.org/@progidev/jss-plugin-formula 404
```

I have over 4000 packages in my lock file. These two are the only ones that errored out. So I have a good reason to think it's not bun's issue.

**Comment by GBonnaire** [comment]
hi,

you need register the `@progidev` private registry 

On repo.gbonnaire.fr with your account, you have how register on npm, translate this for bun in your bunfig.toml

Ref : https://bun.sh/guides/install/registry-scope
