### ISSUE TITLE
Uncaught ReferenceError: jss_copypaste_advanced is not defined

### ISSUE THREAD

**Issue by hatsumihayashi** [GBonnaire/jspreadsheet-plugins-and-editors#4]
Hi.

I'm trying to import copypaste_advanced in JSpreadSheetPro with NPM.
https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/tree/master/plugins/src/copypaste_advanced#npm
When I followed this approach and imported it, I got an error.
![スクリーンショット 2021-06-07 17 08 31](https://user-images.githubusercontent.com/49140783/120995460-61990a80-c7c0-11eb-922e-04f395ea8e01.png)

Temporarily, I commented out L.564 in the local `node_modules/@jspreadsheet/copypaste_advanced/index.js` and the error disappeared.
```
window.jexcel_copypaste_advanced = jss_copypaste_advanced;
↓
//window.jexcel_copypaste_advanced = jss_copypaste_advanced;
```
https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/blob/master/plugins/src/copypaste_advanced/index.js#L564

I would be happy if you could fix it.

Thanks.

**Comment by GBonnaire** [comment]
Hi,

Thank you. I have fixed that and have republished package.

Can you try ?

Thanks

**Comment by hatsumihayashi** [comment]
It's fixed!
Thank you for fixing it so quickly!

**Comment by GBonnaire** [comment]
With pleasure 😊
