### ISSUE TITLE
Mean formulas return 0

### ISSUE THREAD

**Issue by tp-development** [GBonnaire/jspreadsheet-plugins-and-editors#40]
### Plugin Name with version

2.2.9

### JSpreadsheet version

v10.x

### Describe the bug

The average formulas retrieve 0;
![image](https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/98662312/a917cebb-3f67-45d5-9f60-cf88753e3180)

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by GBonnaire** [comment]
Hi,

Thanks for this issue. It's fixed on version 2.2.10 of formulas statistics

Thanks

**Comment by tp-development** [comment]
When the version 2.2.10 of formulas statistics will be available?

**Comment by GBonnaire** [comment]
Hi, sorry error on repo, i have rename this version to 2.3.0 and it already available
