### ISSUE TITLE
Geometric mean retruns Infinity

### ISSUE THREAD

**Issue by tp-development** [GBonnaire/jspreadsheet-plugins-and-editors#41]
### Plugin Name with version

 2.2.10, 2.3.9

### JSpreadsheet version

v10.x

### Describe the bug

The geometric mean returns infinity for a table of positive integers and decimals.

![image](https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/98662312/e984c488-9f7a-4f94-87c0-ffcf35cb5e6e)

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by tp-development** [comment]
[MCT (2).xlsx](https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/files/13368983/MCT.2.xlsx)

**Comment by GBonnaire** [comment]
Hi,

For me, It's normal, this product of this 1000 values is > 1.7976931348623157e+308 (Number.MAX_VALUE)

this value is max supported by your navigator. On Excel you have too an error ? on my sheet excel, i can't make a product and have error.

**Comment by tp-development** [comment]
No, in Excel I am getting proper outcomes: 39,372/4,011 respectively. Obviously, you cannot multiply everything first and then take a root, as you get an enormous number. Maybe do the other way around -> first take a root of n-th degree, and then multiply outcomes. Also, you can multiply numbers in chunks of 5, and then take a root and again, and again.

**Comment by GBonnaire** [comment]
Hi,

i have change with formula with Exp and Ln the result it's very close of your results. With smaller quantity, i have same result with current functions

It's on version 2.3.1

Can you make a feed back after update, to know it's correct ?

**Comment by tp-development** [comment]
Let me check it, keep you updated.
