### ISSUE TITLE
Issues with Fisher test and 2-sample T-test in jss-formulas-statistics

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#42]
### Plugin Name with version

"@progidev/jss-formulas-statistics": "2.3.1"

### JSpreadsheet version

v10.x

### Describe the bug

![image](https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/2717746/464d763f-1a04-4741-b02c-3cf7dc80da75)
![image](https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/2717746/a7221a98-4e5e-4037-ab82-a2296fc3d533)

Cc: @tp-development

**Comment by GBonnaire** [comment]
Hi,

Formula pro is component of JSpreadsheet : @jspreadsheet/formula-pro@4.1.0

But i tested with this version and JSpreasheet version: 10.6.2, and it work.

Do you have error on console ? Can you check if components formula.statistics is loaded ?

**Comment by dmt0** [comment]
Hi @GBonnaire, sorry confused thing. Those formulas are part of `jss-formulas-statistics`, right?

**Comment by GBonnaire** [comment]
Yes, it's confusing... these formulas are implemented with the `jss-formulas-statistics` plugin

There are 3 plugins:
- @jspreadsheet/formula-pro: plugin to create formulas like Excel and create calculation formulas, delivered by the JSpreadsheet teams
- jss-formulas-statistics: adds specific formulas for statistics (Means Formulas, TTest Formulas, Fisher, etc.)
- jss-formula: is a plugin for formula editors (bar and cell) (rename the advanced jss formula editor)

Is it better with this explanation?

**Comment by GBonnaire** [comment]
But can you tell me more in this bug :
Do you have any error in console ?

**Comment by dmt0** [comment]
@tp-development could you please provide the details?

**Comment by dmt0** [comment]
> Is it better with this explanation?

Yeah, I know what they are. Just too easy to mess them up! :)

**Comment by tp-development** [comment]
[stage-green.figlinq.com-1705592947346.log](https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/files/13978726/stage-green.figlinq.com-1705592947346.log)
Hi, this is the log, let me know if it helps.

**Comment by GBonnaire** [comment]
can you activate`debugFormulas: true,` in your configuration of JSpreadsheet workbook ?

and look log.

**Comment by dmt0** [comment]
Seems it was on our side. For some reason some numbers in the sheet got converted to strings like '47', that's why formulas didn't work.
Sorry for false alarm!

**Comment by dmt0** [comment]
Well, I'll let you judge whether it's a good idea for you to try to cast strings to numbers on your end.

**Comment by GBonnaire** [comment]
Hi,

Ok, I search to understand and I don't see what are converted to strings in sheets, can you give me an example ?

**Comment by dmt0** [comment]
<img width="741" alt="image" src="https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/2717746/49afb53f-0c9c-4e63-91bc-be9d226e7cbe">

If you take a look at the first column, from row 12 onwards values became strings. I don't know why, but it's definitely an issue on our side. So nothing to worry about. :)

**Comment by GBonnaire** [comment]
Ok, thanks, It's due with your table overflow options ?

**Comment by dmt0** [comment]
I'm not sure, I still didn't find which operation turns those numbers into strings.

**Comment by dmt0** [comment]
Hi @GBonnaire, seems this issue is not caused by numbers represented as strings. I fixed that part but we still experience this.

I also found that it only happens with jspreadsheet version >=10.5.0. With 10.4.3 things work.

Also the issue is specifically triggered when formulas from statistics plugin are used.

I tried setting `debugFormulas: true,` like you suggested, but didn't get any logs. It's supposed to be at the top level of the `config` object, right?

**Comment by GBonnaire** [comment]
Hi,

debugFormulas is defined like this : 
```JS

    var MyTable = jspreadsheet(document.getElementById('spreadsheet'), {
            debugFormulas: true,
            worksheets: [{
                data: data,
            }],
            plugins: [ /*...*/]
     });
```

i tried to reproduct this bad casting on first column, and with 100 rows, the cast of my values is good. My JSS Version 10.7.2

I ask me : why you have "NAME?" value instead of result. Because if you have strings and numbers, the statistics function convert automaticaly strings to numbers.

"#NAME?" say, the function is unknown, maybe statistics load is not correct ?

how initialize plugin on JSS ? like this ?
```HTML
  <script>
        // JSS Initialisation in HEAD
       jspreadsheet.setLicense("XXXXX");
        //Precision
        formula.adjustPrecision = true;
        // Extensions
        jspreadsheet.setExtensions({ formula, statistics });
    </script>
```

**Comment by dmt0** [comment]
Yeah, my initialization looks pretty much like that. It's at the root of my JS, while I actually use it inside React components. So I know for sure that `setExtensions` executes before anything else.

Another thing that makes it complicated is that this can only be reproduced on one of our developers workstation. Windows, Chrome latest - private mode with no extensions. But for him it happens consistently. Just 3 rows of numbers and `TTEST.TWOSAMPLE.T` will do it.

**Comment by GBonnaire** [comment]
I'm tested on Chrome in guest mode, no error.

<img width="1055" alt="image" src="https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/52194475/ca5f3049-ca06-4011-aee0-46a8869ee962">

And data it's correctly casted, even if i set initial data like string and number

<img width="315" alt="image" src="https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/52194475/af0707c9-04d7-4fc9-8cf7-b09f9ad65398">

Do you have check/clear cache on this workstation ?

on formula, can you test in TTEST.TWOSAMPLES.T with last arg set to TRUE. My idea, maybe JStat lib is in conflict with another in this workstation
`=TTEST.TWOSAMPLES.T(A1:A100,B1:B100,TRUE)`

**Comment by dmt0** [comment]
Yeah, I know on my machine it also works. You can probably figure out the problem through code review. 🤷‍♂️ 
We tried with both TRUE and FALSE, same result.
We did clear cache too.

**Comment by GBonnaire** [comment]
Yes, to resolve this problem, i need reproduct this problem

It's only on chrome on this workstation or all browsers ?

**Comment by tp-development** [comment]
So far we have confirmed the issue on the following configurations:
- Chrome on Debian - bug repro (both issues - open an existing file, reopen the created file with TTest)
- FF on Win10 - bug repro (both issues - open an existing file, reopen the created file with TTest)
- Chrome on Win11 - bug repro (both issues - open an existing file, reopen the created file with TTest)

**Comment by dmt0** [comment]
Hey @GBonnaire , we have a repro here https://stage-green.figlinq.com/create/?fid=StudentDemoB:1302

**Comment by GBonnaire** [comment]
Hi, i have error : Not found on this link

I have try to reproduct on this url, and it work

<img width="453" alt="image" src="https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/52194475/3eb849fe-ff84-4a7a-93f0-a99810ef669b">

**Comment by GBonnaire** [comment]
On this page, i see JSS version : v10.5.0

Do you have try to upgrade to v10.7 ?

**Comment by dmt0** [comment]
Yes, same issue with 10.7. The problem goes away at 10.4.3.

<img width="761" alt="image" src="https://github.com/GBonnaire/jspreadsheet-plugins-and-editors/assets/2717746/25d3ff01-84e5-406a-b671-6e13a1048bf2">

Please try again! I made it public:
https://stage-green.figlinq.com/create/?fid=StudentDemoB:1302

**Comment by GBonnaire** [comment]
Hi,

ok i have access, and i see error, i will check something

**Comment by GBonnaire** [comment]
I see you load 2 version of formula

@jspreadsheet/formula and @jspreadsheet/formula-pro, can you remove @jspreadsheet/formula  and only load formula-pro ?

And check if you have last version to formula-pro : 4.2.0

**Comment by GBonnaire** [comment]
When i test on your file : i have problem, and i have too problem when i write =A3 in cell, that return "NAME?"

**Comment by dmt0** [comment]
Here's what I have:
```
    "@jspreadsheet/formula-pro": "4.2.0",
    "@jspreadsheet/parser": "4.0.5",
    "@jspreadsheet/render": "4.0.0",
    "@jspreadsheet/search": "3.0.1",
    "@jspreadsheet/statusbar": "2.7.1",
    "@progidev/jss-formulas-statistics": "2.3.1",
    "@progidev/jss-plugin-formula": "2.4.1",
```

`@jspreadsheet/formula` is actually a dependency of `jspreadsheet`

```
jspreadsheet@10.5.0:
  version "10.5.0"
  resolved "https://registry.yarnpkg.com/jspreadsheet/-/jspreadsheet-10.5.0.tgz#61419bdd7fa16d4b395e7dbe45cbf69456b3abdb"
  integrity sha512-4cGVaUWcekZIFrhDELLaqm8wzJV5NinqN/cFGeTQF+UY0tL266R2OQ25ZivAZnRGqT/jIWfj/MRk79Yw9B2vXg==
  dependencies:
    "@jspreadsheet/formula" "^2.0.2"
    jsuites "^5.0.28"
```

**Comment by GBonnaire** [comment]
And when you remove only my plugin (statistics) can you try ? i want see on stage difference

**Comment by GBonnaire** [comment]
I don't have access to your link, can you republish your stage env ?

**Comment by dmt0** [comment]
Hey @GBonnaire, I brought the server back up, the link should work.
If I remove your plugin, I also get a `#NAME` thing, but also a JS error somewhere within jspreadsheet code.

**Comment by GBonnaire** [comment]
Can you try to remove one by one plugin, and check ? maybe is not statistics bug an another plugin ?

**Comment by GBonnaire** [comment]
I have some questions :

Do you have Skype to call directly together ?

Do you use formula.setFormula to set new formula or other ?

Do you setExtension before load worksheet ?

Do you have remove plugin to check when there is return to normal.

**Comment by dmt0** [comment]
Hi @GBonnaire 
- setFormula is not used in our code
- setExtension is most definitely run before load worksheet
- as mentioned above, if I remove the plugin, I also get a #NAME thing, but also a JS error somewhere within jspreadsheet code
- yeah, we can definitely Skype, the problem is that I can't repro the problem. Only @tp-development can repro it consistently on multiple machines. (It's a mystery to me how he does it!) But he doesn't have a dev environment, he is not actively working on development. If I can be useful, I sent you an email with my contacts.
