### ISSUE TITLE
Can't load scripts form https://repo.gbonnaire.fr/

### ISSUE THREAD

**Issue by stephen-taylor-dev** [GBonnaire/jspreadsheet-plugins-and-editors#43]
### Plugin Name with version

Print  2.1.4

### JSpreadsheet version

v9.x

### Describe the bug

Possibly a certificate issue?
Error code: SEC_ERROR_EXPIRED_CERTIFICATE
 

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by GBonnaire** [comment]
Hi,

Yes, certificat was renew this monday.

Do you have still error ?

**Comment by stephen-taylor-dev** [comment]
I was yesterday but not anymore. Working well now.
