### ISSUE TITLE
PivotTable plugin for jss V9

### ISSUE THREAD

**Issue by crazyrohila** [GBonnaire/jspreadsheet-plugins-and-editors#8]
Hi,
I found the demo URL for v7 version of jspreadsheet and found the plugin JS file as well (I am using premium version of JSS). But once updated to V9 version recently it throws some error, Can you please with V9 version of PivotTable plugin?
https://jspreadsheet.com/v9/plugins/pivot-table - This page has the code sample but `jss_pivotTable` is undefined with the old plugin code, Can you please help with newer version of Pivot plugin?
@GBonnaire

**Comment by GBonnaire** [comment]
Hi,

The new version of pivotTable is not currently available, I'm working on it. I will publish it soon new version.

Stay tuned here and I'll add a comment to let you know when a new version will be available

**Comment by crazyrohila** [comment]
Thanks a lot for quick response. Is there any rough ETA, so that we can take a decision of using the old one or wait for newer version? (sorry to push-y question but need to finalize something which is dependent on this one :) )

**Comment by GBonnaire** [comment]
ETA : in the next week

**Comment by GBonnaire** [comment]
Hi,

This plugin is now available : https://repo.gbonnaire.fr/product/jss-plugin-pivottable
and demo : https://demo.gbonnaire.fr/jss/plugin.pivottable.php
