### ISSUE TITLE
character order scrambled when entering a formula

### ISSUE THREAD

**Issue by spanneramc** [GBonnaire/jspreadsheet-plugins-and-editors#9]
(using Plotly's grid with this plugin, in Figlinq, you'll receive more info on Figlinq soon):

Typing blindly, there is a scrambling of characters going on.
To move the I-beam cursor, use the arrow keys on the keyboard as soon as you notice the cell contents is wrong.

https://user-images.githubusercontent.com/82650901/191288468-72f286f4-8d2b-46da-a34c-5064c480c7c1.mov

**Comment by GBonnaire** [comment]
Hi, 

Ok, i have reproducted the problem on my other version. I will patch that in next version

**Comment by GBonnaire** [comment]
Hi,

New version is available on https://repo.gbonnaire.fr/product/jss-plugin-formula (2.2.12) with patch

Have good day
